spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/technoboost_dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
